# Netlify configuration for BRANDY-SHOP
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Build environment variables
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

# Specific headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers for API routes (if proxying)
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, apikey"

# Redirects for SPA routing
[[redirects]]
  from = "/api/*"
  to = "https://xrqfckeuzzgnwkutxqkx.supabase.co/rest/v1/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/auth/*"
  to = "https://xrqfckeuzzgnwkutxqkx.supabase.co/auth/v1/:splat"
  status = 200
  force = false

# Admin routes security
[[redirects]]
  from = "/admin-panel/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
  force = false

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Form handling (if using Netlify Forms)
[forms]
  # Enable form detection
  enabled = true

# Functions configuration (if using Netlify Functions)
[functions]
  # Directory for serverless functions
  directory = "netlify/functions"

# Dev server configuration for local development
[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"
  autoLaunch = false
